server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
     gateway:
        ## 开启从注册中心创建路由的功能，利用微服务名字进行路由
        discovery:
           locator:
              enabled: true # 开启从注册中心创建路由的功能，利用微服务名字进行路由
        routes:
           - id: payment_routh  #路由的id没u有固定规则，但是要唯一。
             #uri: http://localhost:8001 #匹配后提供服务的路由地址
             
             #开启从注册中心创建路由的功能，利用微服务名字进行路由
             uri: lb://CLOUD-PROVIDE-USERSERVICE
             predicates: 
               - Path=/user/get/** #断言路径相匹配的进行路由
               
           - id: payment_routh1  #路由的id没u有固定规则，但是要唯一。
             #uri: http://localhost:8001 #匹配后提供服务的路由地址
             
             #开启从注册中心创建路由的功能，利用微服务名字进行路由
             uri: lb://CLOUD-PROVIDE-USERSERVICE
             predicates: 
                - Path=/user/lb/** #断言路径相匹配的进行路由
                
        
eureka:
  client:
    # 表示是否将自己注册进EurekaServer，默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka  #单击
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/   #集群
  instance:
     hostname: cloud-gateway-service
    #instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    # 访问路径可以显示ip地址
#    prefer-ip-address: true
