server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discoveryserver-addr: 127.0.0.1:8848 #配置nacos地址
management:
  endpoints:
    web:
      exposure:
        include: '*'

#把9002注册到8848里面，并且监控所有。