server:
  port: 83
spring:
  application:
    name: nacos-consumer-provider
  cloud:
    nacos:
      discoveryserver-addr: 127.0.0.1:8848 #配置nacos地址
management:
  endpoints:
    web:
      exposure:
        include: '*'

service-url:
  nacos-user-service: http://nacos-payment-provider
